endpoints:
  actuator:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
  shell:
    auth:
      simple:
        user:
          name: admin
          password: admin
info:
  app:
    name: Boot Actuator
    description: Actuator Demo
    version: 1.0.0
